site_name: TRXO â€” Ping Identity Configuration Management
site_description: Manage, compare, and deploy Ping configurations safely and consistently.
site_url: https://trevonix.github.io/trxo   # update if you use custom domain
repo_url: https://github.com/Trevonix/trxo
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - search.highlight
    - search.suggest
nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Usage: usage.md
      - Setup & Authentication: setup_and_auth.md
      - Storage Setup: storage_setup.md
  - Features:
      - Advanced Features: advanced_features.md
      - Batch Operations: batch_operations.md
      - Service Account Tokens: service-account-token-lifetime-and-scopes.md
plugins:
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
